### ISSUE TITLE
Move Watch Live banner above everything else

### ISSUE THREAD

**Issue by richarddubay** [NewSpring/Holtzman#1086]
Having the Watch Live banner show up under the header but before other content breaks up the flow of the thing you're in the middle of. Suggestion is to move it to the very top and push the header down.

![img_0783](https://cloud.githubusercontent.com/assets/3229463/18550377/836c3042-7b21-11e6-99bb-fb42e49f6c93.PNG)

**Comment by samclaridge** [comment]
Just to confirm this is what you're thinking? @jbaxleyiii @richarddubay 
![screenshot 2016-09-15 12 21 01]

![screenshot 2016-09-15 12 29 22](https://cloud.githubusercontent.com/assets/7452283/18558163/0c2a184a-7b40-11e6-93ae-ab44aea03fbf.png)

FWIW we did try that in the design phase but decided against it because of how it pushed the nav and all the content further down the page and removes the ability to tap the status bar to return to top. The current banner is meant to sit above the content and therefore not affect screen real estate - although, from the looks of your screenshot, it seems to be pushing the content down anyway, which is a separate issue. It also requires us to override the series brand color of the status bar when live, otherwise it will look even weirder with the live bar being sandwiched between 2 bars with the different series brand color.

Moreover, it also brings up the question of scroll-away vs fixed, in the proposed implementation the live bar would need to be fixed in order to match and feel consistent with the status bar.

All that to say, I agree that the current implementation isn't perfect, but this is a much more nuanced problem with a lot of constraints and moving pieces. I'm loathe to try and make a snap decision change so close to launch.

**Comment by jbaxleyiii** [comment]
@samclaridge 💯 thank you for the stellar response and reminding me of why we made those calls.

Also, I 100% agree we shouldn't change anything for launch!

More discussions for sure
