### ISSUE TITLE
Giving to Multiple Funds Has Blank Option

### ISSUE THREAD

**Issue by briankalwat** [NewSpring/Holtzman#1572]
## Steps to Reproduce

1. Select a secondary fund to give to.

### Buggy Behavior

An empty option is visible, which is unclear why/what it's for.

### Expected Behavior

Options should include the default `Select Fund`, as well as all active funds.

### Screenshots

![img_0007](https://cloud.githubusercontent.com/assets/2465823/21114732/1423c7ae-c07c-11e6-8167-195d9dabb51b.PNG)

**Comment by jbaxleyiii** [comment]
@briankalwat this is actually intended right now so a user can deselect a fund. I agree it is a less than ideal solution which is why we are redoing this entire form 💯 

https://8f7be55d-e347-43c2-b1d5-81e6dbf87636.sbook.io/?knob-Fund=General%20Fund&knob-Fund%201=General%20Fund&knob-Fund%202=Building%20Fund&selectedKind=Add%20To%20Cart&selectedStory=With%20two%20accounts&full=0&down=1&left=1&panelRight=1&downPanel=storybook-addon-background%2Fbackground-panel
