### ISSUE TITLE
Clicking Saved Accounts doesn't go to saved account section

### ISSUE THREAD

**Issue by dcs619** [NewSpring/Holtzman#1635]
## Steps to Reproduce

Describe how to reproduce this issue.

1. While logged into the app, go to Profile > Saved Accounts.
2. The Give page loads and I have no idea where Saved Accounts is.
3. Scroll all the way to the bottom to find Saved Accounts.

### Buggy Behavior

The give page loads with no indication where my Saved Accounts are.

### Expected Behavior

Clicking Saved Accounts from profile should go to the Saved Accounts section on the giving page.

This behavior was tested on an iPad, but usability applies to other devices as well.

**Comment by samclaridge** [comment]
I think we're actually removing all that from the profile page of the app. Thus, reducing confusion by having 1 single point of entry, via the dashboard

**Comment by dcs619** [comment]
@samclaridge As a user I think it would be a mistake to remove it from the profile.  It's easy to find there; whereas the dashboard/home feed gets too long / requires too far to scroll.

![](https://media.giphy.com/media/TwFQ9kQzFcADK/giphy.gif)

**Comment by samclaridge** [comment]
@dcs619 one of the issues and complaints we currently have in the app is with the routing and navigation (lack of back buttons) not responding as the user expects with giving because we have access to them in multiple places. The thought was that removing them from the profile would solve this by reducing the routes and keeping all giving related info in one place.

Are you looking at the test account page? If so, I would challenge the assertion the page is too long, because the test account has a ton of schedules, which won't be the case in real life. Only a small number of users even have a schedule, let alone multiples. So, the most you would reasonably have on the page is 3 activity cards, a ytd card (mobile only), and 1 schedule, before the saved payment. To me this doesn't translate to an unreasonable amount of scrolling.

I agree that having access to it from the profile is nice. But I question whether it's necessary given all the other factors.

**Comment by jbaxleyiii** [comment]
@samclaridge @dcs619 I think a good "why not both" would be to scroll down to where the saved payment section is in view via a link
