### ISSUE TITLE
Giving Schedule Custom Tag Issue - No way to customize

### ISSUE THREAD

**Issue by morgansmithh** [NewSpring/Holtzman#1823]
## Steps to Reproduce

Describe how to reproduce this issue.

1. Go to /give/now
2. Click "Schedule Contribution," Choose a frequency, and choose a start date _other than_ Custom
3. Change from your previously chosen start date (tomorrow or next month) to "Custom"

### Buggy Behavior

When you go straight through and click schedule, then a frequency, and _then_ "Custom" it will give you the ability to choose a customized start date. Following the previously described dates, however, doesn't present you with any option to select dates yet still keeps "Review Contribution" enabled; therefore, when you click "Review," your schedule details report starting at an invalid date (screenshot below). 

### Expected Behavior

When you click on Custom (regardless of selecting a different start date before it), you should be given calendar to make the schedule customized. If there is no date, the "Review Contribution" should remain disabled. 

### Screenshots

![screen shot 2017-02-20 at 2 23 51 pm](https://cloud.githubusercontent.com/assets/22217299/23139024/7d4eecc6-f778-11e6-80a2-0b46c2eba69c.png)

**Comment by richarddubay** [comment]
@JakeDawkins @delianides @jbaxleyiii I think the problem here is that it doesn't give you a calendar to pick a date from when choosing "Custom" if you've picked a different date choice first. This happens on the web too. Also, you need to have entered a dollar amount first in order for the "Review Contribution" button to be green, but I think this is just a side effect of the calendar not showing. All the "Review" button knows is that there is an amount and two buttons are checked. If you click off of "Custom" and then click it again, the calendar pops up just fine.
