### ISSUE TITLE
Review Contribution styling breaks for 4 digit amounts

### ISSUE THREAD

**Issue by dcs619** [NewSpring/Holtzman#1832]
## Steps to Reproduce

Describe how to reproduce this issue.

1. Enter a three digit amount in `I'd like to give`
2. Click `Review Contribution`, sidebar looks normal
3. Cancel and increase to a four digit amount
4. `Review Contribution` styles wrap to a second line

___
### Buggy Behavior

![screen shot 2017-03-04 at 11 50 57 am](https://cloud.githubusercontent.com/assets/1210933/23580516/8332178c-00d1-11e7-94b1-4e79dbb29580.png)

___
### Expected Behavior

![screen shot 2017-03-04 at 11 50 45 am](https://cloud.githubusercontent.com/assets/1210933/23580518/88f4f496-00d1-11e7-9652-b022c1cbdda8.png)

**Comment by JakeDawkins** [comment]
Dropping the account name to 1/2 instead of 2/3 fixes this (although causes the title to wrap for campus expansion but `¯\_(ツ)_/¯`. 

For the total line, we could drop `Total` to 1/4 and let the amount be 3/4.

This would work for anything under 6-figures 

<img width="712" alt="screen shot 2017-03-04 at 10 26 30 pm" src="https://cloud.githubusercontent.com/assets/9259509/23584258/c0094902-0129-11e7-98a0-91aed7e64167.png">

**Comment by jbaxleyiii** [comment]
@JakeDawkins excellent! Lets do that!
