### ISSUE TITLE
Audio Player doesn't Advance Songs

### ISSUE THREAD

**Issue by delianides** [NewSpring/Holtzman#656]
This could be different for web but on the app when a song is finished playing the next song is loaded and the song length is updated but the scrubber isn't reset so next song can start playing.

**Comment by delianides** [comment]
So far I've tried this on web and the sim and its worked as expected.

**Comment by johnthepink** [comment]
per convo last week, our currently plan is to supply the native player with a playlist, and hope this fixes this issue

**Comment by johnthepink** [comment]
Actually, that's incorrect. We don't need to supply a playlist. I have a hunch the issue is in here https://github.com/NewSpring/Apollos/blob/d208e48f7fe43f390d82c4b9620768d91a4e8e3a/sites/app/modules/app/client/libraries/players/players.audio.js but I'm not sure

**Comment by benwiley** [comment]
Seems like the problem is here: https://github.com/NewSpring/Apollos/blob/d208e48f7fe43f390d82c4b9620768d91a4e8e3a/sites/app/modules/app/client/libraries/players/players.audio.js#L101

Found the duration to be something like 100.777, which becomes 100.8 after the `toFixed`.  The position however stops at 100.702, which becomes 100.7 after the `toFixed`.

**Comment by johnthepink** [comment]
![](http://i.giphy.com/kQg7fQMvVD5Ha.gif)

**Comment by briankalwat** [comment]
@jbaxleyiii this is still broken in the latest beta `0.0.3 (155)` on iOS 10.0.1.

**Comment by delianides** [comment]
This works for me but its intermittent and doesn't advance on certain songs.
